const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),best:document.querySelector('#best'),speed:document.querySelector('#speed'),overlay:document.querySelector('#overlay'),title:document.querySelector('#title'),message:document.querySelector('#message'),action:document.querySelector('#action'),jump:document.querySelector('#jump'),pause:document.querySelector('#pause'),sound:document.querySelector('#sound')};
const W=960,H=430,GROUND=350;let state='ready',last=0,score=0,best=+(localStorage.kichtaBest||0),speed=380,nextObstacle=1.2,sound=true,shake=0;
const cat={x:112,y:GROUND-112,w:132,h:112,vy:0,onGround:true,frame:0,anim:0};const obstacles=[],dust=[],clouds=[{x:130,y:70,s:1},{x:510,y:105,s:.7},{x:800,y:55,s:.9}];
const sprites=new Image();sprites.src='assets/kichta-sprites.webp';const FRAME_W=181,FRAME_H=362;
ui.best.textContent=pad(best);
function pad(n){return Math.floor(n).toString().padStart(5,'0')}
function reset(){score=0;speed=380;nextObstacle=1;obstacles.length=dust.length=0;cat.y=GROUND-cat.h;cat.vy=0;cat.onGround=true;state='running';ui.overlay.classList.add('hidden');}
function jump(){if(state==='ready'||state==='over'){reset();return}if(state==='paused'){togglePause();return}if(cat.onGround){cat.vy=-720;cat.onGround=false;beep(520,.06);for(let i=0;i<7;i++)dust.push({x:cat.x+30,y:GROUND-8,vx:-30-Math.random()*90,vy:-Math.random()*80,r:2+Math.random()*5,a:1})}}
function togglePause(){if(state==='running'){state='paused';show('PAUSE','Kichta reprend son souffle.','CONTINUER')}else if(state==='paused'){state='running';ui.overlay.classList.add('hidden');last=performance.now()}}
function show(k,t,b){ui.title.textContent=t;ui.message.textContent=k==='FIN DE COURSE'?`Score : ${pad(score)} · Record : ${pad(best)}`:'Touche le bouton ou appuie sur P.';ui.action.textContent=b;ui.overlay.querySelector('.eyebrow').textContent=k;ui.overlay.classList.remove('hidden')}
function gameOver(){state='over';shake=12;best=Math.max(best,Math.floor(score));localStorage.kichtaBest=best;ui.best.textContent=pad(best);beep(120,.18);show('FIN DE COURSE','Oups… Kichta a rencontré un obstacle.','REJOUER')}
function spawn(){const types=['box','bin','plant'];let type=types[Math.floor(Math.random()*types.length)],w=type==='box'?54:type==='bin'?46:44,h=type==='box'?55:type==='bin'?76:62;obstacles.push({x:W+30,y:GROUND-h,w,h,type});nextObstacle=.85+Math.random()*1.15-Math.min(.25,score/2500)}
function update(dt){if(state!=='running')return;score+=dt*10;speed=380+Math.min(310,score*1.15);ui.score.textContent=pad(score);ui.speed.textContent=(speed/380).toFixed(1)+'×';cat.vy+=1900*dt;cat.y+=cat.vy*dt;if(cat.y>=GROUND-cat.h){if(!cat.onGround&&cat.vy>300)for(let i=0;i<9;i++)dust.push({x:cat.x+35,y:GROUND-5,vx:-80-Math.random()*100,vy:-Math.random()*100,r:2+Math.random()*5,a:1});cat.y=GROUND-cat.h;cat.vy=0;cat.onGround=true}cat.anim+=dt;if(cat.onGround&&cat.anim>.105){cat.frame=(cat.frame+1)%3;cat.anim=0}else if(!cat.onGround)cat.frame=cat.vy<0?3:4;nextObstacle-=dt;if(nextObstacle<=0)spawn();for(let i=obstacles.length-1;i>=0;i--){let o=obstacles[i];o.x-=speed*dt;if(o.x+o.w<0)obstacles.splice(i,1);else if(cat.x+27<o.x+o.w&&cat.x+cat.w-23>o.x&&cat.y+20<o.y+o.h&&cat.y+cat.h-10>o.y){cat.frame=5;gameOver()}}for(const d of dust){d.x+=d.vx*dt;d.y+=d.vy*dt;d.vy+=250*dt;d.a-=dt*1.8}for(let i=dust.length-1;i>=0;i--)if(dust[i].a<=0)dust.splice(i,1);for(const c of clouds){c.x-=speed*.035*dt;if(c.x<-150)c.x=W+120}}
function draw(){ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.88}let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#dff6d8');g.addColorStop(1,'#f6f0cf');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawClouds();ctx.fillStyle='#aac997';for(let x=-((score*5)%180);x<W;x+=180){ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x+100,190);ctx.lineTo(x+200,GROUND);ctx.fill()}ctx.fillStyle='#789566';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle='#c6a66a';ctx.fillRect(0,GROUND, W,9);for(let x=-((score*speed/80)%70);x<W;x+=70){ctx.fillStyle='#d7bf87';ctx.fillRect(x,GROUND+22,38,5)}for(const d of dust){ctx.globalAlpha=Math.max(0,d.a);ctx.fillStyle='#eadca9';ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,7);ctx.fill()}ctx.globalAlpha=1;for(const o of obstacles)drawObstacle(o);drawCat();ctx.restore()}
function drawClouds(){ctx.fillStyle='#fff9';for(const c of clouds){ctx.beginPath();ctx.arc(c.x,c.y,28*c.s,0,7);ctx.arc(c.x+32*c.s,c.y-8*c.s,38*c.s,0,7);ctx.arc(c.x+70*c.s,c.y,27*c.s,0,7);ctx.fill()}}
function drawCat(){ctx.save();if(state==='over'){ctx.translate(cat.x+cat.w/2,cat.y+cat.h/2);ctx.rotate(-.18);ctx.translate(-(cat.x+cat.w/2),-(cat.y+cat.h/2))}if(sprites.complete&&sprites.naturalWidth)ctx.drawImage(sprites,cat.frame*FRAME_W,0,FRAME_W,FRAME_H,cat.x-20,cat.y-45,cat.w+42,cat.h+55);else{ctx.fillStyle='#695648';ctx.beginPath();ctx.ellipse(cat.x+65,cat.y+58,62,47,0,0,7);ctx.fill()}ctx.restore()}
function drawObstacle(o){if(o.type==='box'){ctx.fillStyle='#a87339';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#6e4724';ctx.lineWidth=3;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.stroke()}else if(o.type==='bin'){ctx.fillStyle='#315b46';ctx.fillRect(o.x,o.y+10,o.w,o.h-10);ctx.fillStyle='#203e30';ctx.fillRect(o.x-5,o.y,o.w+10,13);ctx.fillStyle='#8fe26e';ctx.font='bold 22px sans-serif';ctx.fillText('♻',o.x+10,o.y+49)}else{ctx.fillStyle='#b86442';ctx.fillRect(o.x+7,o.y+30,o.w-14,o.h-30);ctx.fillStyle='#4e8c45';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(o.x+22+(i-1)*8,o.y+22-i*3,13,24,(i-1)*.5,0,7);ctx.fill()}}}
function beep(freq,dur){if(!sound)return;try{const a=new (AudioContext||webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function loop(t){let dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
ui.action.onclick=()=>state==='paused'?togglePause():reset();ui.jump.onclick=jump;ui.pause.onclick=togglePause;ui.sound.onclick=()=>{sound=!sound;ui.sound.textContent=sound?'♪':'×'};canvas.addEventListener('pointerdown',jump);addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump()}if(e.code==='KeyP')togglePause()});requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
