const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d');
const ui={score:$('#score'),kibble:$('#kibble'),speed:$('#speed'),label:$('#third-label'),overlay:$('#overlay'),title:$('#title'),message:$('#message'),action:$('#action'),jump:$('#jump'),fire:$('#fire'),pause:$('#pause'),sound:$('#sound'),cinematic:$('#cinematic')};
const W=960,H=430,GROUND=354,BOSS_AT=260;let mode='ready',last=0,score=0,kibble=0,speed=360,nextObs=1.1,nextBrick=2.2,bossTimer=0,victoryTime=0,sound=true,shake=0,worldX=0;
const cat={x:118,y:GROUND-105,w:126,h:105,vy:0,onGround:true,frame:0,anim:0};
const obstacles=[],bricks=[],particles=[],shots=[];const clouds=[{x:120,y:70,s:1},{x:520,y:105,s:.7},{x:820,y:58,s:.9}];
const catImgs=Array.from({length:6},(_,i)=>{const x=new Image;x.src=`assets/kichta/run-${i}.webp`;return x});const pucci=new Image;pucci.src='assets/pucci-boss.webp';
const alleyFiles=['alley-bg.webp','alley-market.webp','alley-industrial.webp','alley-moon.webp'];
const alleys=alleyFiles.map(f=>{const x=new Image;x.src='assets/'+f;return x});
const sceneOrder=[{b:0,c:0,f:0},{b:1,c:1,f:0},{b:2,c:2,f:0},{b:3,c:0,f:0},{b:1,c:2,f:1},{b:0,c:1,f:1},{b:3,c:2,f:1},{b:2,c:0,f:1},{b:0,c:2,f:0},{b:2,c:1,f:0},{b:1,c:0,f:1},{b:3,c:1,f:0}];
const watcher={timer:3+Math.random()*3,life:0,x:480,y:235,blink:0};
const boss={x:755,y:GROUND-150,w:190,h:150,hp:3,flash:0,dying:0};
const bossLayer=document.createElement('canvas');bossLayer.width=190;bossLayer.height=150;const bctx=bossLayer.getContext('2d');
function pad(n){return Math.floor(n).toString().padStart(5,'0')}
function reset(){score=0;kibble=0;speed=360;nextObs=1;nextBrick=1.7;bossTimer=0;victoryTime=0;worldX=0;obstacles.length=bricks.length=particles.length=shots.length=0;Object.assign(cat,{y:GROUND-cat.h,vy:0,onGround:true,frame:0});Object.assign(boss,{hp:3,flash:0,dying:0});ui.cinematic.pause();ui.cinematic.currentTime=0;ui.cinematic.classList.add('hidden');mode='run';ui.overlay.classList.add('hidden');hud()}
function hud(){ui.score.textContent=pad(score);ui.kibble.textContent=`${kibble} / 10`;ui.fire.disabled=kibble<10||!['run','boss'].includes(mode);ui.fire.classList.toggle('ready',kibble>=10);ui.fire.querySelector('span').textContent=kibble>=10?'TIR PRÊT':`TIR ${kibble}/10`;ui.label.textContent=mode==='boss'?'BOSS':'VITESSE';ui.speed.textContent=mode==='boss'?'PUCCI':(speed/360).toFixed(1)+'×'}
function show(tag,title,msg,button){ui.overlay.querySelector('.eyebrow').textContent=tag;ui.title.textContent=title;ui.message.textContent=msg;ui.action.textContent=button;ui.overlay.classList.remove('hidden')}
function jump(){if(mode==='ready'||mode==='over'||mode==='won'){reset();return}if(mode==='paused'){resume();return}if(cat.onGround&&['run','boss'].includes(mode)){cat.vy=-740;cat.onGround=false;burst(cat.x+35,GROUND-5,'#e9d8a0',7);beep(520,.05)}}
function fire(){if(kibble<10||!['run','boss'].includes(mode))return;kibble=0;shots.push({x:cat.x+105,y:cat.y+35,w:44,h:18,v:780,boss:mode==='boss'});shake=3;beep(850,.12);hud()}
function pause(){if(['run','boss'].includes(mode)){mode='paused';show('PAUSE','Kichta reprend son souffle.','Appuie sur Continuer ou sur P.','CONTINUER')}}
function resume(){mode=score>=BOSS_AT?'boss':'run';ui.overlay.classList.add('hidden');last=performance.now();hud()}
function addKibble(x,y){kibble=Math.min(10,kibble+1);particles.push({x,y,vx:0,vy:-95,r:10,a:1.4,type:'kibble'});beep(720,.045);hud()}
function enterBoss(){mode='boss';obstacles.length=bricks.length=0;bossTimer=1.2;shake=8;hud();particles.push({x:W/2,y:90,vx:0,vy:0,r:1,a:2.4,type:'bossText'})}
function gameOver(){mode='over';cat.frame=5;shake=13;beep(120,.2);show('FIN DE COURSE','Oups… Kichta a été touchée.',`Score : ${pad(score)} · Croquettes : ${kibble}/10`,'REJOUER')}
function bossExplosion(stage){const pos=stage===1?[boss.x+42,boss.y+125]:stage===2?[boss.x+150,boss.y+128]:[boss.x+95,boss.y+76];particles.push({x:pos[0],y:pos[1],vx:0,vy:0,r:stage===3?110:55,a:1.15,type:'boom',stage});burst(pos[0],pos[1],stage===3?'#fff2a1':'#ff8b3d',stage===3?70:34);shake=stage===3?30:16;beep(stage===3?75:145,stage===3?.55:.28)}
function win(){mode='bossEnding';boss.dying=1.7;obstacles.length=shots.length=0;bossExplosion(3)}
function startCinematic(){mode='cinematic';ui.cinematic.classList.remove('hidden');ui.cinematic.currentTime=0;ui.cinematic.play().catch(()=>{mode='won';show('VICTOIRE !','Kichta entre au paradis des chats !','La cinématique est prête : touche Rejouer pour recommencer.','REJOUER')})}
function spawnObstacle(fromBoss=false){if(!fromBoss&&bricks.some(b=>b.x>W-250)){nextObs=.75;return}const types=fromBoss?['ball','box','bin']:['box','bin','plant'];const type=types[Math.floor(Math.random()*types.length)];let w=type==='box'?54:type==='bin'?46:type==='ball'?42:44,h=type==='box'?55:type==='bin'?76:type==='ball'?42:62;obstacles.push({x:fromBoss?boss.x-15:W+25,y:GROUND-h,w,h,type,fromBoss,passed:false,v:fromBoss?-(410+Math.random()*90):0})}
function spawnBrick(){if(obstacles.some(o=>!o.fromBoss&&o.x>W-300)){nextBrick=.8;return}bricks.push({x:W+35,y:190+Math.random()*25,w:62,h:38,hit:false,bump:0});nextBrick=2.6+Math.random()*2.2}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*180,vy:-40-Math.random()*160,r:2+Math.random()*5,a:1,type:'dust',color})}
function update(dt){if(!['run','boss','bossEnding'].includes(mode))return;if(mode==='bossEnding'){boss.dying-=dt;updateParticles(dt);if(boss.dying<=0)startCinematic();return}
  const prevY=cat.y;score+=dt*(mode==='boss'?3:10);if(mode==='run'&&score>=BOSS_AT)enterBoss();speed=360+Math.min(240,score*.75);worldX+=speed*dt;cat.vy+=1950*dt;cat.y+=cat.vy*dt;if(cat.y>=GROUND-cat.h){if(!cat.onGround)burst(cat.x+35,GROUND-4,'#eadca9',8);cat.y=GROUND-cat.h;cat.vy=0;cat.onGround=true}cat.anim+=dt;if(cat.onGround&&cat.anim>.095){cat.frame=(cat.frame+1)%3;cat.anim=0}else if(!cat.onGround)cat.frame=cat.vy<0?3:4;
  if(mode==='run'){nextObs-=dt;nextBrick-=dt;if(nextObs<=0){spawnObstacle();nextObs=.9+Math.random()*1.05}if(nextBrick<=0)spawnBrick()}else{bossTimer-=dt;boss.flash=Math.max(0,boss.flash-dt);if(bossTimer<=0){spawnObstacle(true);bossTimer=1.05+Math.random()*.55}}
  for(let i=bricks.length-1;i>=0;i--){const b=bricks[i];b.x-=speed*dt;b.bump=Math.max(0,b.bump-dt);if(!b.hit&&cat.x+cat.w-22>b.x&&cat.x+22<b.x+b.w&&cat.y+cat.h-12>b.y&&cat.y+12<b.y+b.h){b.hit=true;b.bump=.18;addKibble(b.x+b.w/2,b.y);burst(b.x+b.w/2,b.y,'#f6c753',8)}if(b.x+b.w<0)bricks.splice(i,1)}
  for(let i=obstacles.length-1;i>=0;i--){const o=obstacles[i];o.x+=(o.fromBoss?o.v:-speed)*dt;if(o.fromBoss&&!o.passed&&o.x+o.w<cat.x){o.passed=true;addKibble(cat.x+cat.w/2,cat.y)}if(o.x+o.w<-30){obstacles.splice(i,1);continue}if(hit(cat,o)){gameOver();return}}
  for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.x+=s.v*dt;burst(s.x,s.y+8,'#ffe369',1);if(mode==='boss'&&s.x+s.w>=boss.x+25){shots.splice(i,1);boss.hp--;boss.flash=.3;if(boss.hp>0)bossExplosion(3-boss.hp);else win();continue}for(let j=obstacles.length-1;j>=0;j--)if(hit(s,obstacles[j])){burst(obstacles[j].x,obstacles[j].y,'#ffd65a',18);obstacles.splice(j,1);shots.splice(i,1);break}if(s.x>W+80&&shots[i])shots.splice(i,1)}updateParticles(dt);updateEyes(dt);hud()}
function updateEyes(dt){if(watcher.life>0){watcher.life-=dt;watcher.blink+=dt}else{watcher.timer-=dt;if(watcher.timer<=0){const spots=[[92,246],[485,242],[865,255],[700,224]];const s=spots[Math.floor(Math.random()*spots.length)];watcher.x=s[0]+(Math.random()-.5)*25;watcher.y=s[1]+(Math.random()-.5)*15;watcher.life=1.8+Math.random()*1.6;watcher.timer=5+Math.random()*6;watcher.blink=0}}}
function updateParticles(dt){for(const p of particles){if(!['bossText','boom'].includes(p.type)){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.type==='kibble'?50*dt:280*dt}p.a-=dt}for(let i=particles.length-1;i>=0;i--)if(particles[i].a<=0)particles.splice(i,1)}
function hit(a,b){return a.x+25<b.x+b.w&&a.x+a.w-22>b.x&&a.y+18<b.y+b.h&&a.y+a.h-8>b.y}
function draw(){ctx.save();if(shake){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.86}drawSky();drawEyes();ctx.fillStyle=['boss','bossEnding'].includes(mode)?'#3c3047cc':'#332b2aaa';ctx.fillRect(0,GROUND,W,H-GROUND);ctx.fillStyle='#c48f58';ctx.fillRect(0,GROUND,W,7);for(let x=-(worldX%72);x<W;x+=72){ctx.fillStyle='#8e6751';ctx.fillRect(x,GROUND+24,38,4)}for(const b of bricks)drawBrick(b);for(const o of obstacles)drawObstacle(o);if(['boss','bossEnding'].includes(mode))drawBoss();drawCat();for(const s of shots)drawShot(s);drawParticles();ctx.restore()}
function drawScene(slot,x){const s=sceneOrder[(slot%sceneOrder.length+sceneOrder.length)%sceneOrder.length],im=alleys[s.b];if(!im.complete||!im.naturalWidth){ctx.fillStyle='#33294f';ctx.fillRect(x,0,W,H);return}const sw=Math.min(im.naturalWidth,1120),sx=Math.min(im.naturalWidth-sw,s.c*150);if(s.f){ctx.save();ctx.translate(x+W,0);ctx.scale(-1,1);ctx.drawImage(im,sx,0,sw,im.naturalHeight,0,0,W,H);ctx.restore()}else ctx.drawImage(im,sx,0,sw,im.naturalHeight,x,0,W,H)}
function drawSky(){const slot=Math.floor(worldX/W),off=-(worldX%W);drawScene(slot,off);drawScene(slot+1,off+W);if(['boss','bossEnding'].includes(mode)){ctx.fillStyle='#2a163b55';ctx.fillRect(0,0,W,H)}}
function drawEyes(){if(watcher.life<=0)return;const blink=Math.sin(watcher.blink*7)>0.94?.18:1,fade=Math.min(1,watcher.life*2);ctx.save();ctx.globalAlpha=fade;const g=ctx.createRadialGradient(watcher.x,watcher.y,3,watcher.x,watcher.y,52);g.addColorStop(0,'#000e');g.addColorStop(1,'#0000');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(watcher.x,watcher.y,62,42,0,0,7);ctx.fill();ctx.fillStyle='#ffe348';ctx.shadowColor='#ffdf2f';ctx.shadowBlur=14;for(const dx of [-13,13]){ctx.beginPath();ctx.ellipse(watcher.x+dx,watcher.y,7,5*blink,-.15*Math.sign(dx),0,7);ctx.fill();if(blink>.5){ctx.fillStyle='#1b0c05';ctx.beginPath();ctx.ellipse(watcher.x+dx+1,watcher.y,2,5,0,0,7);ctx.fill();ctx.fillStyle='#ffe348'}}ctx.restore()}
function drawCat(){const im=catImgs[cat.frame];if(im.complete&&im.naturalWidth)ctx.drawImage(im,cat.x-42,cat.y-55,210,184);else{ctx.fillStyle='#745d49';ctx.fillRect(cat.x,cat.y,cat.w,cat.h)}}
function drawBrick(b){const y=b.y-(b.bump?8*Math.sin((.18-b.bump)/.18*Math.PI):0);ctx.fillStyle=b.hit?'#94724a':'#c77c33';ctx.fillRect(b.x,y,b.w,b.h);ctx.strokeStyle='#6e431e';ctx.lineWidth=3;ctx.strokeRect(b.x,y,b.w,b.h);ctx.fillStyle=b.hit?'#6e543b':'#ffe067';ctx.font='bold 24px sans-serif';ctx.fillText(b.hit?'·':'?',b.x+23,y+28)}
function drawObstacle(o){if(o.type==='ball'){ctx.fillStyle='#e65757';ctx.beginPath();ctx.arc(o.x+21,o.y+21,21,0,7);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.arc(o.x+21,o.y+21,12,0,7);ctx.stroke()}else if(o.type==='box'){ctx.fillStyle='#aa7338';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.strokeStyle='#6b431d';ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.stroke()}else if(o.type==='bin'){ctx.fillStyle='#315b46';ctx.fillRect(o.x,o.y+10,o.w,o.h-10);ctx.fillStyle='#203e30';ctx.fillRect(o.x-5,o.y,o.w+10,13);ctx.fillStyle='#8fe26e';ctx.font='22px sans-serif';ctx.fillText('♻',o.x+10,o.y+49)}else{ctx.fillStyle='#b86442';ctx.fillRect(o.x+7,o.y+30,o.w-14,o.h-30);ctx.fillStyle='#4e8c45';for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(o.x+22+(i-1)*8,o.y+22-i*3,13,24,(i-1)*.5,0,7);ctx.fill()}}}
function drawBoss(){bctx.clearRect(0,0,190,150);if(pucci.complete)bctx.drawImage(pucci,0,0,190,150);bctx.save();bctx.globalCompositeOperation='destination-out';if(boss.hp<=2){bctx.beginPath();bctx.arc(40,128,25,0,7);bctx.fill()}if(boss.hp<=1){bctx.beginPath();bctx.arc(148,128,30,0,7);bctx.fill();bctx.beginPath();bctx.arc(112,136,22,0,7);bctx.fill()}bctx.restore();if(boss.flash)ctx.globalAlpha=.45+Math.random()*.4;if(boss.hp>0||boss.dying>1.05)ctx.drawImage(bossLayer,boss.x,boss.y);ctx.globalAlpha=1;ctx.fillStyle='#2d2038dd';ctx.fillRect(675,16,260,48);ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.fillText('PUCCI · 3 MISSILES',695,39);for(let i=0;i<3;i++){ctx.fillStyle=i<boss.hp?'#8dff68':'#492d43';ctx.fillRect(785+i*44,48,36,7)}}
function drawShot(s){ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=s.boss?'#ff694f':'#ffe051';ctx.beginPath();ctx.moveTo(44,9);ctx.lineTo(8,0);ctx.lineTo(0,9);ctx.lineTo(8,18);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-14,6,24,6);ctx.restore()}
function drawVictory(){const t=victoryTime;const bowlX=655,bowlY=GROUND-28;ctx.fillStyle='#d44b54';ctx.beginPath();ctx.ellipse(bowlX,bowlY,72,22,0,0,Math.PI);ctx.lineTo(bowlX+55,bowlY+24);ctx.quadraticCurveTo(bowlX,bowlY+38,bowlX-55,bowlY+24);ctx.closePath();ctx.fill();ctx.fillStyle='#7a4b35';ctx.beginPath();ctx.ellipse(bowlX,bowlY,59,13,0,0,7);ctx.fill();ctx.strokeStyle='#fff9';ctx.lineWidth=5;for(let i=0;i<3;i++){const x=bowlX-30+i*30;ctx.beginPath();ctx.moveTo(x,bowlY-16);ctx.bezierCurveTo(x-15,bowlY-38-(t*15)%18,x+15,bowlY-55-(t*15)%18,x,bowlY-75);ctx.stroke()}const im=catImgs[4];if(im.complete)ctx.drawImage(im,470,GROUND-150+Math.sin(t*7)*3,205,180);ctx.fillStyle='#304329cc';ctx.fillRect(170,45,620,72);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 30px sans-serif';ctx.fillText('PUCCI EST VAINCU !',480,78);ctx.fillStyle='#a8ff83';ctx.font='bold 17px sans-serif';ctx.fillText('La récompense de Kichta : une bonne gamelle de pâtée',480,103);ctx.textAlign='left'}
function drawParticles(){for(const p of particles){ctx.globalAlpha=Math.max(0,Math.min(1,p.a));if(p.type==='bossText'){ctx.fillStyle='#342641cc';ctx.fillRect(225,78,510,68);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 30px sans-serif';ctx.fillText('BOSS FINAL : PUCCI',480,115);ctx.font='bold 14px sans-serif';ctx.fillStyle='#ffe56e';ctx.fillText('Trois missiles sont nécessaires pour le vaincre !',480,137);ctx.textAlign='left'}else if(p.type==='boom'){const k=1-p.a/1.15,rr=p.r*(.35+k);ctx.save();ctx.globalCompositeOperation='lighter';const g=ctx.createRadialGradient(p.x,p.y,3,p.x,p.y,rr);g.addColorStop(0,'#fff');g.addColorStop(.2,'#fff59a');g.addColorStop(.5,'#ff7b27');g.addColorStop(1,'#d8190000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,rr,0,7);ctx.fill();ctx.strokeStyle='#fff3a0';ctx.lineWidth=7*(1-k);ctx.beginPath();ctx.arc(p.x,p.y,rr*.8,0,7);ctx.stroke();ctx.restore()}else if(p.type==='kibble'){ctx.fillStyle='#d88c2f';ctx.beginPath();ctx.moveTo(p.x,p.y-8);ctx.lineTo(p.x+9,p.y);ctx.lineTo(p.x,p.y+8);ctx.lineTo(p.x-9,p.y);ctx.closePath();ctx.fill()}else{ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}}ctx.globalAlpha=1}
function beep(f,d){if(!sound)return;try{const a=new(AudioContext||webkitAudioContext),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}catch{}}
function loop(t){const dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
ui.cinematic.onended=()=>{mode='won';show('VICTOIRE !','Kichta entre au paradis des chats !','Pucci est vaincu après trois missiles. Kichta peut enfin savourer sa pâtée.','REJOUER')};ui.action.onclick=()=>mode==='paused'?resume():reset();ui.jump.onclick=jump;ui.fire.onclick=fire;ui.pause.onclick=()=>mode==='paused'?resume():pause();ui.sound.onclick=()=>{sound=!sound;ui.sound.textContent=sound?'♪':'×'};canvas.addEventListener('pointerdown',jump);addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump()}if(e.code==='KeyF')fire();if(e.code==='KeyP')mode==='paused'?resume():pause()});hud();requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
